airbnb/knowledge-repo

README.md
@airbnb/knowledge-app-maintainers
=> fix for jan's comment

knowledge_repo/repositories/gitrepository.py
Currently migrating the embedded tooling repository is not possible due to persistence of branches and git objects in the the submodule. This patch adds support for automatic migrations.
=> Fix automatically migrating submodule remotes.

README.md, knowledge_repo/app/templates/about.html
This updates about.html to have the current README content. We should fix the about.html to have the /about content surface the README itself, or open a configuration to specify about content, but this fixes it for now.
@airbnb/knowledge-app-maintainers
=> update about.html and add more R to the readme

knowledge_repo/repositories/gitrepository.py
Older versions of git do not support extracting the remote repository uri using:
`git remote get-url <remote_name>`
This PR patches it to use the gitpython `Remote.url` attribute.
=> Fix reading git remote uri in older versions of git.

knowledge_repo/_version.py, knowledge_repo/app/app.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/render.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/posts.py, resources/server_config.py, tests/config_server.py
The pypi package only updates when the stable branch is tagged with a release, so we should do that. 
@earthmancash @danfrankj @matthewwardrop
=> Match stable to master for the release

knowledge_repo/postprocessors/extract_images.py
Solves issue with tilde paths in local images
https://github.com/airbnb/knowledge-repo/issues/53
@airbnb/knowledge-app-maintainers @airbnb/knowledge-app-owners
=> expand tilde paths for local images

INTHEWILD.md, README.md
Update the readme to use pip, not git+ssh (I think this is the last mention of it) 
Add INTHEWILD file so we can see who's using the KR!
@matthewwardrop @earthmancash @danfrankj
=> Update readme + add in the wild file

knowledge_repo/app/models.py
Incorporates idea and feedback from https://github.com/airbnb/knowledge-repo/pull/80.
=> handle none case in excluded tags

knowledge_repo/app/routes/tags.py
@earthmancash 
@matthewwardrop
=> fix for tags page when excluded tags is not configd

README.md
Response to https://github.com/airbnb/knowledge-repo/issues/91
@NiharikaRay @matthewwardrop @danfrankj
=> Specify where configuration files are in the README

knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/error.html
The HTML in base.html is not valid HTML. This patch fixes that, and begins neatening some of the other templates. A more complete review/cleanup of the HTML templates will be left to future work, since there's quite a bit of redesign coming up in the pipeline.
=> Fix some invalid HTML and neaten some more.

knowledge_repo/app/app.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/__init__.py, knowledge_repo/app/routes/groups.py, knowledge_repo/app/routes/render.py, knowledge_repo/app/templates/add_group_users.html, knowledge_repo/app/templates/all_groups.html, knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/markdown-base.html, knowledge_repo/app/templates/post_groups.html, knowledge_repo/app/templates/view_group_users.html, knowledge_repo/postprocessors/format_checks.py
@earthmancash @matthewwardrop @danfrankj 
The long awaited PR that adds the front-end + parsing to groups. The best way to explain this is through a combination of words and pictures, so here goes. 
In the YAML headers, if there's an private flag, we add the appropriate status, and add the groups to the groups associated with the post. By default, we add a group, entitled `group.post_id`, that is the "custom group" per post. 
If you are the author of a post, and your post has the private flag, you will see this link at the top of your rendered post with "Add Permissions" as the text (this is where the old "Edit on Github" links were)
This brings you to this page
Clicking on "View Users" brings you to:
And on "Add Users", you get a typeahead, similar to what's on the Post Editor
If you …
=> [Permissions] Add parsing + front-end

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
As contributions grow, we should probably have all of us tagged in PRs to increase throughput and on issues, to increase visibility on them.
@NiharikaRay @matthewwardrop @earthmancash @danfrankj
=> [Github] Auto-tag people in issues + PRs

knowledge_repo/repositories/gitrepository.py
Port has to be explicitly casted to int , and [0-9] should be more strict than \d
Test Plan: 
=> changed \d to [0-9] and cast port to int

knowledge_repo/converters/html.py
Add a reasonable height to proxy posts and a link to their original source
@NiharikaRay @matthewwardrop @earthmancash
=> add a reasonable height to proxy posts as well as a link to the original source

knowledge_repo/app/app.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/web_editor.py, knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/create-knowledge.html
WIP
Do we only want to allow webeditor if the WEB_EDITOR_PREFIXES has a list of prefixes? 
@NiharikaRay @matthewwardrop @earthmancash
=> a quick fix for handling of prefixes that are web-editable

knowledge_repo/app/models.py, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/utils/posts.py
Description of changeset: There was an issue (https://github.com/airbnb/knowledge-repo/issues/94) where certain parameters weren't being passed through correctly. I use javascript now to get existing parameters, and accordingly create the new hrefs. 
Also, cleaned up the way author search was done!
Test Plan: Ensure pagination works as expected on the /feed page
=> [Search] Fix parameter passing + author search

knowledge_repo/app/utils/posts.py
We pushed out changes to fill out the keywords field, this PR uses that column for searching! Fixes https://github.com/airbnb/knowledge-repo/issues/90 and makes search way better
Test Plan: 
Tested locally by searching `lisa reviews`, `chetan sharma` and some others
=> search by keywords now that the column is filled

knowledge_repo/app/templates/index-base.html
@NiharikaRay have a look. Not sure if this is more band-aid then you'd like.
Test Plan: 
=> check that next-btn exists before adding href in cluster view

knowledge_repo/app/routes/stats.py
@NiharikaRay quick fix to the cum post stats. PTAL
Test Plan: 
=> Sort weeks before calculating cumulative status

knowledge_repo/app/routes/comment.py, knowledge_repo/app/templates/email_templates/comment_email.txt, knowledge_repo/app/templates/email_templates/review_email.txt, knowledge_repo/app/templates/email_templates/reviewer_request_email.txt, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/utils/emails.py, tests/test_emails.py
Currently our links to posts in emails are broken - this commit fixes those
=> fix email paths for reviewing and commenting

knowledge_repo/app/utils/emails.py
Add missing _external argument needed in url_for to get the full URL
=> add missing _external argument to url_for to get the full url

knowledge_repo/app/templates/post_editor_base.html
Quickfix
@matthewwardrop @NiharikaRay
=> use the error message in the alert when saving posts

knowledge_repo/app/routes/web_editor.py
Also fix a tuple -> multiline string bug
@matthewwardrop 
@NiharikaRay
=> web editors can save even if not author (editors are admin)

.gitattributes, knowledge_repo/app/templates/about.html, knowledge_repo/app/templates/markdown-presentation.html
- Updated incorrect stylesheet path `filename='css/codehilite.css'` to `filename='css/codehilite-friendly.css'`. 
- Updated CSS for /about page to make it easier to read.
Test Plan: 
n/a
=> CSS Cleanup

knowledge_repo/repositories/dbrepository.py
@matthewwardrop @NiharikaRay @earthmancash 
As discussed - adding an update field 
WARNING: if you already have a DB Repo you'll have to add a new column
=> Add updated_at to DBKnowledgeRepository database tables

knowledge_repo/app/index.py, knowledge_repo/app/routes/editor.py
@NiharikaRay @earthmancash @matthewwardrop
=> on publish or unpublish, reindex even if we have checked recently

run_tests.sh
similar to https://github.com/airbnb/knowledge-repo/pull/210, but there's another place where style check takes place.
=> also exclude deploys in run_tests.sh style checks

knowledge_repo/app/app.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/post_editor_base.html, knowledge_repo/app/templates/web_posts.html
Description of changeset: As per discussion on #214, I created a Jinja filter here that takes care of date formatting.
Test Plan: 
Grepped through this repo to find instances of `strftime` and converted them to using this filter.
Auto-reviewers:  @matthewwardrop @earthmancash @danfrankj
=> [Knowledge] Move date formatting to Jinja filter

knowledge_repo/postprocessors/extract_images.py
Users have been reported (and I have experienced) dropping of various figures from knowledge posts. This is at least part of the problem. I've written a more sophisticated regex expression which now allows more flexible image tags (and does not group them together inadvertently).
Test Plan: 
Run on more complicated markdown scripts to ensure that the images are all collected.
=> Fix skipping some images based on too simple a regex.

knowledge_repo/app/templates/index-base.html
Incorporating feedback from previous PR. Thanks Nikki for the simple way to prevent default event bubbling!
=> Small cleanups to pagination code.

knowledge_repo/app/routes/tags.py
=> Fix pagination on tag pages.

README.md, appveyor.yml, run_tests.bat
Some of our users are running the `knowledge_repo` on Windows, and recent updates have broken Windows installations. To prevent this going forward, this patch adds continuous integration for the Windows platform.
=> Add Windows continuous integration tests.

knowledge_repo/app/index.py
Currently the indexing code makes assumptions about how booleans will be translated to strings and stored in the database (as a string). Different database backends do this differently, leading to inconsistent results (e.g. #203). This patch fixes this.
=> Fix confused datatypes during index locking/unlocking.

knowledge_repo/app/templates/create-knowledge.html
Simple change to make proxy posts an option.
@matthewwardrop 
@NiharikaRay
=> add proxy posts as an option

knowledge_repo/app/routes/posts.py
This route does not require the post to be published 
@NiharikaRay @matthewwardrop
=> add a preview route that does not require posts to be published

knowledge_repo/app/models.py, knowledge_repo/app/static/css/custom.css, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/converters/html.py, run_tests.sh, tests/test_posts/addition_priciples.ipynb, tests/test_posts/one_plus_one.ipynb, tests/test_posts/riemann_hypothesis.ipynb
This PR addresses the following issues:
- Loading posts with many code blocks is very slow (should fix #243). This was caused by code highlighting attempting to auto-detect the language that should be lexed. This has been disabled.
- Fixed logging bug in Python 2 (whereby errors in various endpoints would not get logged due to use of Python 3 features)
- Fixes global show/collapse of code blocks in knowledge posts (incorporates some of the fixes in #253), and renames css classes to be more recognisable
- Properly handles HTML output from code in Jupyter / Rmd notebooks, which means Plotly and other interactive code should now work (fixes #238, and motivation behind #253)
- Added some dummy posts for easier testing of various features, and to make screenshotting of various renderings …
=> Miscellaneous fixes and improvements, covering enhanced performance, rendering, and plotly support.

knowledge_repo/converters/html.py
This fixes some of the workarounds needed by #259 .
=> Fix cell output globbing preventing html tags from being collected by markdown preprocessors.

knowledge_repo/templates/repo_data_readme.md
=> fix typing error

knowledge_repo/app/app.py, knowledge_repo/app/deploy/common.py, knowledge_repo/app/deploy/gunicorn.py, knowledge_repo/app/deploy/uwsgi.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/posts.py, knowledge_repo/app/utils/render.py, knowledge_repo/app/utils/search.py, knowledge_repo/config.py, knowledge_repo/config_defaults.py, knowledge_repo/converters/html.py, knowledge_repo/mapping.py, knowledge_repo/postprocessors/format_checks.py, knowledge_repo/repositories/dbrepository.py, knowledge_repo/repositories/gitrepository.py, knowledge_repo/utils/dependencies.py, run_tests.sh, tests/test_posts/unicode.md
This sits on top of #292, and will be merged after it. Fixes #261.
=> Fix broken unicode support for posts in Python2

knowledge_repo/app/auth_providers/oauth2.py
Hi all,
Sorry I didn't manage to get my testing in in time for the merge of https://github.com/airbnb/knowledge-repo/pull/305 - I've now tested this in production and after patching a few minor bugs, everything works great!
I left some reviews in the PR thread (which explain these changes) but thought it might make it easier for you if I collect my suggestions together in this small patchset.
=> OAuth Bitbucket fixes

INTHEWILD.md
Description of changeset: Add Postmates to `INTHEWILD`
=> add Postmates

knowledge_repo/app/auth_provider.py, knowledge_repo/app/auth_providers/debug.py, knowledge_repo/app/auth_providers/oauth2.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/templates/auth-switcher.html, knowledge_repo/app/templates/base.html
@matthewwardrop 
* Add missing imports so that authentication providers don't reference undefined variables 
* Add messaging for when a user reaches a resource that requires authentication but no authentication providers are configured 
* Remove unused imports 
* Fix inconsistent handling of avatar images  
* Add email and login for github authentication provider to be used as identifier
* Add exceptions when authentication providers are not configured with client secret / key or when autherntication providers do not return the requried information
=> debug authentication providers

knowledge_repo/app/templates/about.html, knowledge_repo/templates/repo_data_readme.md
Update some outdated documentation
Addresses https://github.com/airbnb/knowledge-repo/issues/330
Test Plan: 
None 
=> update install documentation

knowledge_repo/repositories/folder.py
Update the folder repository so that 
1) it doesn't break when getting arguments like `branch` from upstream code 
2) Can init into already created folders
3) Writes references into the folder 
Test Plan: 
```
mkdir test_folder_repo
knowledge_repo --repo test_folder_repo init 
knowledge_repo --repo test_folder_repo create ipynb example.ipynb
knowledge_repo --repo test_folder_repo add example.ipynb -p 'projects/example'
knowledge_repo --repo test_folder_repo runserver
```
Begins to address https://github.com/airbnb/knowledge-repo/issues/332
Auto-reviewers:  @matthewwardrop
=> update folder repo

INTHEWILD.md
=> adds Recursion Pharma to INTHEWILD.md

knowledge_repo/app/config_defaults.py, resources/server_config.py
This fixes the (ironically) explicitly stated caveat of setting the index interval greater than the index timeout.  Additionally, the `server_config.py` file under `resources` is updated to match the current set of config variables under `app.config_defaults.py`.
Test Plan: 
None
=> Update server config

knowledge_repo/repository.py
kwargs gets overwritten by iterating over postprocessors
=> Bugfix: postprocessor kwargs

docs/deployment.rst
=> extract_images_to_s3.py link fix.

docs/deployment.rst
Fix broken link to default repository config.
=> Fix broken link: repository_config.yml

knowledge_repo/app/auth_providers/oauth2.py
I was getting a redirect_uri with to many slashes:
```
http://sub.example.com///oauth/....
```
This should fix the issue.
Test Plan: 
I could not find tests for `OAuthProvider`, but I will try to work on that when I have time.
=> Avoid multiple slashes in oauth redirect_uri

INTHEWILD.md
=> Add ASI Data Science to organisations using knowledge-repo

knowledge_repo/app/models.py, knowledge_repo/repositories/dbrepository.py
Fixes to indexing, including properly closing connections and writing repo revision to the DB
See Issue #430 
Test Plan: 
=> Db connection fixes

knowledge_repo/app/index.py
@CPapadim This resolves my issues about database connections failing in oblique ways. Does this solve your issues too?
Replaces #445 (and solves #430)
=> Dispose of engine on child thread before performing operations.

INTHEWILD.md
Add Databricks to list of orgs using knowledge repo
Test Plan: 
N/A
=> Add Databricks to list of orgs using knowledge repo

INTHEWILD.md
ASI Data Science has relaunched as Faculty, but is still happily using knowledge-repo :D
Description of changeset: Update outdated link to ASI Data Science and rename to Faculty.
Test Plan: N/A
=> Add Faculty to INTHEWILD

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Matthew is probably the only one really looking at these anymore so we should just remove this altogether. 
None
Last time...
=> remove auto-reviewers who are not watching anyways

knowledge_repo/_version.py, knowledge_repo/app/app.py, knowledge_repo/app/routes/editor.py, setup.py
Fixing a few build/CI issues as the Knowledge Repo doesn't pin many of its dependencies and newer packages have caused breaking changes. 
Test Plan: 
CI.
to: @etr2460 @NiharikaRay
=> [ci] Fixing build/CI issues

INTHEWILD.md
Adds Built In to INTHEWILD.md
Thanks for this awesome tool!
=> Add Built In to INTHEWILD.md

knowledge_repo/_version.py
Release version 0.8.9 with new bug fixes and remove Niharika from the authors list (Thanks for your service Niharika!)
to: @john-bodley @NiharikaRay @serenajiang
=> Bump version to 0.8.9

.travis.yml
=> Publish releases based on the python 3.5 build

.travis.yml, setup.py
Users running the KR workflow often run it in OSX, so it seems worthwhile to add it to Travis.
cc @bulam @etr2460
=> Add Mac to Travis environment matrix

docs/requirements.txt
Fix #519 by refreshing the `requirements.txt` file used by Read the Docs to kick off a documentation build.
cc @bulam
=> DOC update requirements.txt for Read the Docs build

knowledge_repo/app/deploy/common.py
Found a bug in #547.
Test Plan:
=> fix bug in assertion

knowledge_repo/app/templates/markdown-presentation.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/post_editor_base.html
Closes #481.
This might be more relevant to rendering the KP in HTML but probably doesn't hurt anyway to bump the MathJax version.
Tested on local server
=> Update MathJax config

knowledge_repo/app/templates/markdown-presentation.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/post_editor_base.html, knowledge_repo/post.py
Closes #503, closes #490
Fixes #489, fixes #483 
Combining the YAML header detection issues addressed by #489 and #483.
Tested by processing a known good Jupyter notebook locally through `knowledge_repo add`.
=> Header parsing

knowledge_repo/app/auth_providers/oauth2.py
=> Handle nested and list identifier keys for OAuth response

knowledge_repo/app/auth_providers/ldap.py, knowledge_repo/app/config_defaults.py
=> Updates to ldap_auth branch

knowledge_repo/_version.py, knowledge_repo/app/auth_providers/ldap.py, knowledge_repo/app/config_defaults.py, knowledge_repo/app/templates/auth-login-form.html
Closes #416 with a rebase and separating out commits from #393
Test Plan:
=> Add LDAP authorization

INTHEWILD.md, knowledge_repo/_version.py
Thanks for maintaining this! We love it :D
=> YouGov uses knowledge repos, too!

knowledge_repo/_version.py
Bumping the version to 0.9.0 to release to PyPi. There's been 139 commits since the last release and a major UI update.
Test Plan: 
NA
=> Bumping version to 0.9.0

knowledge_repo/repositories/gitrepository.py
The `GitKnowledgeRepository` class has an internal function `__remote_available` which is used to check if there is network connectivity to the remote git repo before attempting to execute a `fetch` or `push` to the repo.
This works for most `http` and `ssh` git repos , however it does not work in the case of an `ssh` repo where there is no direct connectivity to the ssh server, but rather there is an ssh configuration which proxies the connection through an intermediary server.
Currently with this kind of repository setup Knowledge Repo will abort fetches, and raise an exception for pushes even though there is actually no connectivity issue.
This PR removes the `__remote_available` function, and replaces it with some try-except blocks which should achieve the same intention, but also …
=> Improve connectivity check for git repositories

knowledge_repo/_version.py
Remove duplicate dependency `pyyaml` (line 21).
=> Remove duplicate dependency pyyaml

knowledge_repo/app/models.py, knowledge_repo/app/routes/groups.py, scripts/knowledge_repo, tests/test_gitposts.py
This PR is the beginnings of some miscellaneous cleanups thoughout the app, particularly as pertaining to data model usage. This is not urgent, but clears the way for some upcoming PRs regarding url and reindexing cleanups. Also no where near finished.
=> Miscellaneous clean ups

.travis.yml
Add Python 3.9 to test matrix
Test Plan:
=> add new versions to CI matrix

knowledge_repo/app/deploy/gunicorn.py
What?
=====
* Port relevant sections of code from `gunicorn.app.base.Application` into `knowledge-repo.app.deploy.gunicorn.GunicornDeployer` to use the `--config` supplied by the user.
Why?
=====
* We'd like to instrument our deployment of Knowledge-Repo with some observability metrics and being able to customize our gunicorn deployment is the way we do that with other apps right now.
This builds off of https://github.com/airbnb/knowledge-repo/pull/437 where a user can supply their own arguments. Unfortunately, while I can see that it does indeed bring in my `GUNICORN_CMD_ARGS='--config gunicorn.conf.py` it does not actually load it up. I stole some code from [gunicorn's source](https://github.com/benoitc/gunicorn/blob/ee685e197b3f7cf899dc7d6e0688ff169e9d10df/gunicorn/app/base.py#L173-L180 …
=> Allow users to load their own Gunicorn config

.travis.yml
Reverts airbnb/knowledge-repo#582
@csharplus
=> Revert "add new versions to CI matrix"

docs/installation.rst
Add the detailed commands to set up knowledge-repo through a virtual environment.
Test Plan: 
The listed commands have been tested locally on a Macbook.
=> Update installation.rst to provide commands for setting up through a virtual environment

docker/README.md
Add some instructions to solve a common port number issue when 7000 is occupied
Test Plan: 
CI
@JJJ000
=> Update docker README.md with a command for running locally with a different port number

knowledge_repo/config.py, knowledge_repo/converter.py, knowledge_repo/post.py, knowledge_repo/repository.py
Clean up the import statements by sorting in alphabetical order 
Test Plan: 
CI
Reviewers:
@JJJ000
=> Sort import statements in alphabetical order

knowledge_repo/_version.py, knowledge_repo/repositories/dbrepository.py, knowledge_repo/repositories/folder.py, knowledge_repo/repositories/gitrepository.py, knowledge_repo/repositories/meta.py, knowledge_repo/utils/encoding.py, knowledge_repo/utils/exec_code.py, knowledge_repo/utils/git.py, knowledge_repo/utils/import_submodules.py, knowledge_repo/utils/types.py
Remove unused imports and sort imports in alphabetical order.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Adjust the sequence of import statements based on alphabetical order

knowledge_repo/app/auth_providers/debug.py, knowledge_repo/app/auth_providers/ldap.py, knowledge_repo/app/auth_providers/oauth2.py
The files in the `auth_provider` module have been updated with sorted import statements. 
Test Plan: 
CI
Reviewers:
@JJJ000
=> Update import statements to be sorted

knowledge_repo/app/deploy/common.py, knowledge_repo/app/deploy/gunicorn.py, knowledge_repo/app/deploy/uwsgi.py, knowledge_repo/app/migrations/env.py, knowledge_repo/app/routes/auth.py, knowledge_repo/app/routes/comment.py, knowledge_repo/app/routes/debug.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/routes/groups.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/routes/stats.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/routes/vote.py
Import statements in many files are not well organized, which has been cleaned up.
Test Plan:
CI
Reviewers:
@JJJ000
=> Clean up and sort import statements

knowledge_repo/app/app.py, knowledge_repo/app/auth_provider.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/permissions.py, knowledge_repo/app/roles.py, knowledge_repo/app/utils/auth.py, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/image.py, knowledge_repo/app/utils/posts.py, knowledge_repo/app/utils/render.py, knowledge_repo/app/utils/requests.py, knowledge_repo/app/utils/time.py
Sort import statements in alphabetical order, and remove unused imports.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Make code clean-ups relevant to import statements

knowledge_repo/app/config_defaults.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/stats.py, knowledge_repo/converters/gdoc.py, knowledge_repo/converters/html.py, knowledge_repo/converters/ipynb.py, knowledge_repo/converters/org.py, knowledge_repo/converters/pdf.py, knowledge_repo/converters/pkp.py, knowledge_repo/converters/proxy.py, knowledge_repo/converters/rmd.py, knowledge_repo/post.py, knowledge_repo/postprocessors/extract_images.py, knowledge_repo/postprocessors/extract_images_to_local.py, knowledge_repo/postprocessors/extract_images_to_s3.py, knowledge_repo/postprocessors/format_checks.py, knowledge_repo/repository.py, knowledge_repo/utils/encoding.py, knowledge_repo/utils/git.py
Some code related to datetime and import statements has been simplified.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Clean up datetime related references and import statements in multiple modules

knowledge_repo/_version.py, knowledge_repo/app/auth_provider.py, knowledge_repo/app/auth_providers/debug.py, knowledge_repo/app/auth_providers/ldap.py, knowledge_repo/app/routes/debug.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/utils/image.py, knowledge_repo/constants.py, knowledge_repo/converter.py, knowledge_repo/converters/gdoc.py, knowledge_repo/converters/html.py, knowledge_repo/converters/ipynb.py, knowledge_repo/converters/pdf.py, knowledge_repo/postprocessors/extract_images.py, knowledge_repo/postprocessors/format_checks.py
Consolidate some hard-coded string constants into one shared file.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Move some constants to a shared file

knowledge_repo/config.py, knowledge_repo/config_defaults.py, knowledge_repo/converter.py, knowledge_repo/post.py
Some refactoring is made to clean up string formatting.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Simplify string formatting based on latest approaches

knowledge_repo/app/index.py, knowledge_repo/postprocessors/extract_images.py, knowledge_repo/postprocessors/extract_images_to_s3.py, knowledge_repo/repositories/folder.py, knowledge_repo/repositories/meta.py
Clean up the code related to string formatting.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Update string formats with the latest approach

knowledge_repo/app/routes/posts.py, knowledge_repo/repositories/folder.py, knowledge_repo/repositories/gitrepository.py, knowledge_repo/utils/files.py, knowledge_repo/utils/registry.py
Make a code refactoring to ease template setting.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Create a share method get_path to simplify setting templates

.gitignore, knowledge_repo/app/routes/auth.py, knowledge_repo/app/routes/comment.py, knowledge_repo/utils/dependencies.py
Made fixes for some lint violations based on `pycodestyle`.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Exclude VSCode settings and fix a few lint issues

knowledge_repo/_version.py, knowledge_repo/app/auth_providers/ldap.py, knowledge_repo/app/auth_providers/oauth2.py, knowledge_repo/app/deploy/__init__.py, knowledge_repo/app/deploy/common.py, knowledge_repo/app/deploy/gunicorn.py, knowledge_repo/app/migrations/env.py, knowledge_repo/app/routes/debug.py, knowledge_repo/app/routes/editor.py
Reformatting some long code lines to fix the lint warnings.
Test Plan: 
CI
Reviewers:
@JJJ000
=> [hw] Fix the lint issues for some long lines

knowledge_repo/app/routes/auth.py, knowledge_repo/app/routes/comment.py, knowledge_repo/app/routes/debug.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/routes/groups.py, knowledge_repo/app/routes/health.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/routes/stats.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/routes/vote.py, knowledge_repo/app/utils/auth.py, knowledge_repo/app/utils/image.py, knowledge_repo/app/utils/posts.py, knowledge_repo/app/utils/shared.py
Some duplicated code for Blueprint creation has been consolidated.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Add a shared method for Blueprint creation

docs/deployment.rst
Add details to setup knowledge repo
Test Plan: 
[x]ci
@csharplus
=>  Add details to setup knowledge repo

knowledge_repo/config.py, knowledge_repo/converter.py, knowledge_repo/post.py, knowledge_repo/repository.py, tests/test_cluster.py, tests/test_comments.py, tests/test_emails.py, tests/test_favorites.py, tests/test_feed.py, tests/test_gitposts.py, tests/test_table.py, tests/test_tags.py, tests/test_webeditorposts.py
reformat code
Test Plan: 
[x]CI
@csharplus
=> reformat unit test code

knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/render.py, knowledge_repo/app/utils/search.py
Some lint formatting issues have been addressed.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Adjust line formatting to resolve lint issues

knowledge_repo/post.py, knowledge_repo/repositories/stub.py
For exceptions, log the error messages; Reformat long lines to avoid lint issues.
Test Plan:
CI
Reviewers:
@JJJ000
=> Log the error messages for exceptions and reformat long lines to fix lint issues

.gitignore, .vscode/settings.json, knowledge_repo/config.py, knowledge_repo/repository.py
Check in the recommended settings for VSCode to ease setting up the development environment.
Test Plan:
CI
Reviewers:
@JJJ000
=> Add recommended vscode settings

knowledge_repo/repositories/gitrepository.py
fix logger format issue
Test Plan: 
[x]CI
@csharplus
=> fix logger format issue

.vscode/settings.json
remove auto format from vscode setting
Test Plan: 
[x]CI
@csharplus
=> remove auto format from vscode setting

.github/workflows/main.yml, knowledge_repo/_version.py
Add maintainers and python version
Test Plan: 
[x]CI
@csharplus
=> Add maintainer and python version

.vscode/settings.json, knowledge_repo/app/models.py, knowledge_repo/app/templates/404.html, knowledge_repo/app/templates/add_group_users.html, knowledge_repo/app/templates/all_groups.html, knowledge_repo/app/templates/auth-login-form.html, knowledge_repo/app/templates/auth-switcher.html, knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/batch_tags.html, knowledge_repo/app/templates/create-knowledge.html, knowledge_repo/app/templates/error.html, knowledge_repo/utils/encoding.py
1. add back auto format settting
2. update query logic
3. fix html format issues
Test Plan: 
[x] CI
@csharplus
=> Improve code quality

.gitignore, knowledge_repo/postprocessors/format_checks.py
Update gitignore with a new file to neglect.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Update gitignore to exclude a local test artifact

knowledge_repo/app/routes/debug.py, knowledge_repo/app/utils/time.py, knowledge_repo/converters/html.py, knowledge_repo/postprocessors/extract_images.py, knowledge_repo/postprocessors/extract_images_to_local.py, knowledge_repo/postprocessors/extract_images_to_s3.py
Some code has been refactored to improve code quality.
Test Plan:
CI
Reviewers:
@JJJ000
=> Refactoring to improve code quality

knowledge_repo/repositories/folder.py
Print out error messages when exceptions were encountered.
Test Plan:
CI 
Reviewers:
@JJJ000
=> Print out exception messages to help debug

knowledge_repo/_version.py
Bumping the version to 0.9.1 to release to PyPi to ship fixs for recent flask breaking changes.
Test Plan: 
[x] CI
@csharplus @bulam
=> bump to v 0.9.1

knowledge_repo/repository.py
Made some code cleanups.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Resolve a few lint errors, and clean up some code

.github/workflows/publish-to-pypi.yml
add git action to publish package to pypi
Test Plan: 
[x]test pypi
@csharplus @etr2460
=> add git action to publish package to pypi

.github/workflows/main.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/publish-to-test-pypi.yml
Try remove package release condition
Test Plan: 
@csharplus
=> fix publish release

docs/requirements.txt
fix doc installment requirement
Test Plan: 
[x] ci
[x] Readthedoc build
@csharplus
=> fix doc installment requirement

docs/requirements.txt
try fix doc deployment
Test Plan: 
ci
doc build
@csharplus
=> try fix doc deployment

knowledge_repo/converters/gdoc.py, knowledge_repo/converters/proxy.py
the previous code would unintentionally match https://docsXgoogle.com/...
=> remove unintentional wildcard from URL checks

docker/Dockerfile, docker/config.py, docker/entrypoint.sh, requirements.txt
fix package dependency to support local server
Test Plan: 
[x]ci
@csharplus
=> fix package dependency to support local server

knowledge_repo/app/auth_providers/oauth2.py
Test Plan: 
test locally
@csharplus
=> fix google authentication failure

.github/workflows/main.yml, .gitignore, knowledge_repo/_version.py, knowledge_repo/app/app.py, knowledge_repo/app/index.py, requirements.txt
1.  index_failure when service start
2. PostgreSQL close unexpectedly the connection issue
Test Plan: 
local build
@csharplus
=> fix index and db bugs

.github/PULL_REQUEST_TEMPLATE.md
Add a `Reviewers` section in the pull request template.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Update pull request template to have reviwers

.github/workflows/main.yml, knowledge_repo/_version.py, requirements.txt, scripts/knowledge_repo_v2
Checkin in This script is intended to created a seperate v2 process wroking in parallel with existing knowledge_repo
At this stage, v2 behavior will 100% match with exsiting worflow
Test Plan: 
N/A
Reviewers:
@csharplus
=> knowledge v2

knowledge_repo_v2/docker/docker-compose.yml
add volumes  and auto sync in docker compose
Test Plan: 
docker-compose up -d
docker exec -it [container_name]
Reviewers:
@csharplus
=> [kp2]add volumes  and auto sync in docker compose

knowledge_repo_v2/docker/docker-compose.yml, knowledge_repo_v2/service/.env.dev, knowledge_repo_v2/service/Dockerfile, knowledge_repo_v2/service/app.py, knowledge_repo_v2/service/config.py, knowledge_repo_v2/service/entrypoint.sh, knowledge_repo_v2/service/manage.py, knowledge_repo_v2/service/requirements.txt
add docker image for db
Test Plan: 
Reviewers:
@csharplus
=> [kp2] add docker image for db

knowledge_repo_v2/docker/docker-compose.yml, knowledge_repo_v2/service/.env.dev, knowledge_repo_v2/service/Dockerfile, knowledge_repo_v2/service/app.py, knowledge_repo_v2/service/requirements.txt
fix db manage connection issue
psycopg2==2.9.4 is required for M1 mac
Test Plan: 
Reviewers:
@csharplus
=> [kp2] fix db manage connection issue

knowledge_repo_v2/service/poetry.lock, knowledge_repo_v2/service/pyproject.toml, knowledge_repo_v2/service/requirements.txt, knowledge_repo_v2/service/setup.sh
add poetry and setup acript
Test Plan: 
[x] CI
Reviewers:
@csharplus
=> [kp2] poetry and  setup script

knowledge_repo_v2/service/app.py, knowledge_repo_v2/service/migrations/README, knowledge_repo_v2/service/migrations/alembic.ini, knowledge_repo_v2/service/migrations/env.py, knowledge_repo_v2/service/migrations/script.py.mako, knowledge_repo_v2/service/migrations/versions/333b583e5612_create_init_tables.py, knowledge_repo_v2/service/poetry.lock, knowledge_repo_v2/service/pyproject.toml, knowledge_repo_v2/service/requirements.txt, knowledge_repo_v2/service/setup.sh
combine all kp1 db migration files into single one
Test Plan: 
[x] CI
Reviewers:
@csharplus
=> [kp2]add initial  db migration

README.md
add support slack channel
Test Plan: 
[x] CI
Reviewers:
@csharplus
=> [kp]add support slack channel

knowledge_repo/_version.py, scripts/setup_script/ec2_setup.sh
bump to 0.9.2 and add ec2 setup script
Test Plan: 
Reviewers:
@csharplus
=> bump to 0.9.2

requirements.txt
update requirements file
Test Plan: 
[x] CI
Reviewers:
@csharplus
=> [kp]update requirements file

.vscode/launch.json, docker/config.py
add db based kp config
Test Plan: 
[x] ci
Reviewers:
=> [kp]add db based kp config

.gitignore, knowledge_repo/app/index.py, knowledge_repo/app/models.py
fix index of webpage post
Test Plan: 
[x] CI
[x] dev
Reviewers:
=> [KG] fix index of webpage post

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, docker/config.py, knowledge_repo/_version.py, knowledge_repo/utils/s3.py, requirements.txt
A utility module is added to support s3 cloud storage.
Test Plan:
CI
Reviewers:
=> Add a utility file for s3 storage operations

docker/config.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/templates/create-knowledge.html, knowledge_repo/app/templates/post_editor_base.html, knowledge_repo/app/templates/post_editor_ipynb.html, knowledge_repo/constants.py, knowledge_repo/converters/ipynb_v2.py, knowledge_repo/utils/s3.py, requirements.txt
- Enable jupyter notebook upload post editor 
- This pr only enables the ability to upload and render a html version of jupyter notebook (if it is a ipynb file, s3 will download the file to your local instead of displaying it. todo: will try to fix it in next pr) 
Test Plan:
Local Dev
Reviewers:
=> Enable Jupyter Notebook Upload Post Editor

knowledge_repo/repositories/gitrepository.py, run_tests.sh
`.knowledge_repo_config.py` should not present in normal situations, thus the related Git read exception could be neglected.
Test Plan:
CI
Reviewers:
=> Avoid printing out an expected exception

knowledge_repo/app/routes/index.py
update app domain url for seo url generator
Test Plan:
[x] CI
Reviewers:
=> [kp]update app domain url for seo url generator

knowledge_repo/app/routes/index.py
old
<lastmod>2023-01-03 00:00:00</lastmod>
new
<lastmod>2023-01-01T23:48:37+00:00</lastmod>
Test Plan:
[x] CI
Reviewers:
=> [kp] fix site-map date format

knowledge_repo/app/routes/editor.py, knowledge_repo/app/templates/index-feed.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/post_editor_base.html, knowledge_repo/app/templates/post_editor_ipynb.html, tests/test_gitposts.py
- change from distinct views to all views
- hide created_at and updated_at fields for ipynb post editor
Test Plan:
local dev
Reviewers:
=> update views and metadata

setup.py
fix pypi deploy error
Test Plan:
[x] CI
Reviewers:
=> [kp]fix pypi deploy error

knowledge_repo/_version.py
bump version to 0.9.2
Test Plan:
[x]CI
Reviewers:
=> [kp]bump version to 0.9.2

knowledge_repo/app/templates/post_editor_base.html
as title
Test Plan:
local dev
Reviewers:
=> [kp] fix undefined created and updated date

knowledge_repo/app/config_defaults.py, scripts/email_client_example.py
Provide an example on how to set up an email client.
Test Plan:
CI
Reviewers:
=> Add an email client example to the scripts

knowledge_repo/app/proxies.py, knowledge_repo/app/routes/editor.py
as title
Test Plan:
local dev
Reviewers:
=> [kp] update s3/notion client 

knowledge_repo/app/routes/editor.py, knowledge_repo/repositories/dbrepository.py, knowledge_repo/repositories/folder.py, knowledge_repo/repositories/gitrepository.py, knowledge_repo/repositories/meta.py, knowledge_repo/repositories/s3repositorty.py, knowledge_repo/repositories/stub.py, knowledge_repo/repository.py, knowledge_repo/utils/files.py
integrate s3 repo with notebook upload flow
Test Plan:
[x] local dev
Reviewers:
=> [kp] integrate s3 repo with notebook upload flow

knowledge_repo/app/routes/index.py, knowledge_repo/app/templates/sitemap.xml
add site-map-posts endpoint
Test Plan:
[x]CI
Reviewers:
=> [kp] add site-map-posts endpoint

knowledge_repo/_version.py, requirements.txt
To avoid potential build issues, the version numbers of a few critical libraries were set to be fixed.
Test Plan:
CI
Reviewers:
=> Lock the version numbers of a few libraries

knowledge_repo/app/static/css/pages/index-feed.css, knowledge_repo/app/static/modules/bootstrap/css/bootstrap.min.css, knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/templates/index-feed.html, knowledge_repo/app/utils/requests.py
- update ui
- add page size selector
Test Plan:
local dev
Reviewers:
=> [kp] update homepage ui 

knowledge_repo/_version.py, knowledge_repo/utils/gcs.py, requirements.txt
add gcs utils
Test Plan:
[x]ci
Reviewers:
=> [kp] add gcs utils

knowledge_repo/app/templates/base.html
add test GA script
Test Plan:
[x] verify in GA console
Reviewers:
=> [kp] add test GA script

knowledge_repo/app/templates/create-knowledge.html
fix post upload icon
Test Plan:
[x] CI
Reviewers:
=> [kp]fix post upload icon

knowledge_repo/app/routes/index.py, knowledge_repo/app/static/robots.txt
1. generate list post based on data from DB directly
2. add / back allow list
Test Plan:
[x] CI
[x] Local test
Reviewers:
=> [KP] fix SEO error

knowledge_repo/app/templates/create-knowledge.html, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/utils/requests.py
as title
Test Plan:
local dev
Reviewers:
=> [KP] update upload method and default result number

requirements.txt
psycopg2-binary
Test Plan:
[x] CI
Reviewers:
=> [kp] fix requirements dependency

knowledge_repo/app/static/css/pages/index-feed.css, knowledge_repo/app/static/js/pages/index-feed.js, knowledge_repo/app/templates/index-feed.html
as title
Test Plan:
local dev
Reviewers:
=> [kp] update tldr expander

knowledge_repo/utils/s3.py
fix s3 repo bug for empty folder
Test Plan:
[x] ci
Reviewers:
=> [kp]fix s3 repo bug for empty folder

.github/workflows/main.yml, knowledge_repo/app/routes/editor.py, knowledge_repo/repositories/s3repositorty.py
fix md data error and ipynb upload
Test Plan:
[x] local test
Reviewers:
=> [kp] fix md data error and ipynb upload

knowledge_repo/app/auth_providers/oauth2.py
fix git authentication
and enable dual authentication
Test Plan:
[x] local build
Reviewers:
=> [kp]fix git authentication

knowledge_repo/app/templates/stats.html
The upper bound for the y axis was set to 750, which needs to be removed to allow dynamic adjustment.
Test Plan:
CI
Reviewers:
=> Remove the limit of y values in the daily pageview chart

knowledge_repo/app/templates/post_editor_base.html
as title
Test Plan:
local dev
Reviewers:
=> [kp] web post form UI fix

.vscode/launch.json, knowledge_repo/app/config_defaults.py, knowledge_repo/app/proxies.py, knowledge_repo/app/routes/editor.py, knowledge_repo/repositories/gcsrepositorty.py, knowledge_repo/repositories/s3repositorty.py, knowledge_repo/utils/gcs.py, knowledge_repo/utils/s3.py
fix some error of gs and s3
Test Plan:
[x] CI
Reviewers:
=> [kp]fix some error of gs and s3

knowledge_repo/app/routes/editor.py, knowledge_repo/repositories/gcsrepositorty.py, knowledge_repo/repositories/s3repositorty.py
Test Plan:
[x]local test
Reviewers:
=> [kp] fix post download

requirements.txt
fix install
Test Plan:
local
Reviewers:
=> [kp]fix install

scripts/setup/setup.sh
add setup script
Test Plan:
[x] CI
Reviewers:
=> [kp]add setup script

knowledge_repo/app/routes/editor.py, knowledge_repo/utils/notion.py, knowledge_repo_v2/service/app/routes/editor.py
as title
Test Plan:
local dev
Reviewers:
=> update notion post link prefix

README.md
as title
Test Plan:
local dev
Reviewers:
=> update Github readme

knowledge_repo/post.py, knowledge_repo/repositories/s3repositorty.py, knowledge_repo/utils/s3.py
as title
Test Plan:
local dev
Reviewers:
=> [kp] add html file into .kp folder

knowledge_repo/_version.py
create new release
Test Plan:
[x]ci
Reviewers:
=> [kp]create new release

knowledge_repo/app/routes/editor.py
as title
Test Plan:
local dev 
Reviewers:
=> [kp] remove unused s3 upload

knowledge_repo/app/static/css/pages/auth-switcher.css, knowledge_repo/app/templates/auth-switcher.html
Adjust the layout of the sign-in page.
Test Plan:
CI
Reviewers:
=> Refine the sign-in page layout

knowledge_repo/app/auth_providers/oauth2.py
fix bitbucket authentication caused by code bug to handle dictionary of bitbucket authentication
Test Plan:
[x]ci
[x]in UI
Reviewers:
=> [kp]fix bitbucket authentication
