knowledge_repo/app/routes/web_editor.py
Recent changes to the setup.py file mean that PyPDF2 is now treated as a soft dependency. This fixes one last lingering hard reference to PyPDF2.
=> Fix hard dependency on PyPDF2

knowledge_repo/app/app.py, knowledge_repo/repositories/meta.py, knowledge_repo/repository.py, scripts/knowledge_repo
This fixes an old hack to get repository uris into the app, in the process fixing gunicorn deploy. It also adds the _kp_uuid method dispatcher for MetaKnowledgeRepository, to again support multiple repositories.
=> Fix knowledge_repo deploy, MetaKnowledgeRepository missing _kp_uuid, and add a common *.uris method for KnowledgeRepository instances.

knowledge_repo/app/routes/web_editor.py
This fixes an issue with path encoding when using the Webeditor flow. If a post is already published, a there's a change made and you click the `Save` button, the path is not encoded correctly, and this throws an error.
=> [Unicode] Quick fix encoding error

knowledge_repo/app/routes/render.py
Another one line fix - there's no reason to log an action that's not instantiated by the user, and that also clutters up the logs 
@earthmancash @matthewwardrop @danfrankj
=> [Logging] Remove logging for typeahead

.travis.yml
@NiharikaRay I think it should probably be your username and password here, given that you are the package's official maintainer.
Just run in this repo on this branch:
`gem install travis`
`travis encrypt --add deploy.password`
And then change the pypi username to your username.
=> Set up auto deployment of package to pypi based on tags in the stable branch

knowledge_repo/_version.py
Currently the `knowledge_repo` script checks to see if it is in a git checked out copy of the knowledge-repo repository, and if so appends the git revision to the version number. If not running in a git repository, this results in a spurious "fatal" error. Suppressing stderr from this command solves the problem, as in this patch.
=> Suppress spurious git fatal messages when not running in a git repository.

knowledge_repo/app/app.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/render.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/posts.py, resources/server_config.py, tests/config_server.py
While we have the concept of excluded tags, the tags and the posts weren't being excluded everywhere. This PR makes sure that all posts with excluded tags are hidden from everywhere. 
Test Plan: 
Add a "private" tag to the post and make sure it is not visible in any route
PTAL @matthewwardrop @danfrankj @earthmancash
=> [Feature] Make sure excluded tags are excluded everywhere

knowledge_repo/_version.py
I had a release tag for 0.6.4, but I didn't bump the version here.
@earthmancash @danfrankj @matthewwardrop
=> Bump version to 0.6.4

README.md, knowledge_repo/_version.py
Currently we have been using the ssh protocol to both install and setup the embedded tooling for knowledge_repo, which was required during the closed beta; but is now causing difficulties for people who have not set up public key authentication with Github. This patch solves this by using the https protocol.
Closes #57 .
=> Use https rather than git protocol to both install and embed tooling.

scripts/knowledge_repo
This adds a '--version' option to the knowledge_repo script that shows both the locally installed version and the embedded/active version of the script. This should make it easier for users to check which version they are running.
=> Add option '--version' to knowledge_repo script.

knowledge_repo/repositories/gitrepository.py, scripts/knowledge_repo
The automatic embedding of tooling seems to be causing some confusion and is really only a boon in a large deployment. This patch disables it by default. Embedding the tooling can be done using done using:
`knowledge_repo --repo <target_repo> init --tooling-embed`
=> Disable the embedding of knowledge_repo tooling by default

knowledge_repo/app/app.py
This is the bug noted in https://github.com/airbnb/knowledge-repo/pull/60 and in https://github.com/airbnb/knowledge-repo/issues/72. 
If excluded tags was not in the server config, this would be None, and the for loop would fail. 
@matthewwardrop @earthmancash @danfrankj
=> [Bugfix] Default excluded tags to empty

knowledge_repo/postprocessors/extract_images.py
Fixes #75 . The addition of the binary flag works on Python 2 also, where it serves as documentation.
=> Fix encoding errors when using reading images from files in extract_images in Python 3.

knowledge_repo/app/routes/index.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/posts.py
It looks like there is an implicit dependency on EXCLUDED_TAGS althroughout the app, which was not picked up earlier. Fixing.
=> Actually fix dependence on possibly absent EXCLUDED_TAGS server configuration.

knowledge_repo/app/app.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/render.py, knowledge_repo/app/templates/base.html, knowledge_repo/app/utils/search.py
@matthewwardrop @danfrankj @earthmancash 
The much awaited search ranking PR. What this does: 
1. Actually fills in the keywords column, by combining the author, title, tldr, and tags of a post, and removing stopwords. 
2. Use the typeahead search to create a SQL statement where we rank the search results by the number of search terms that are present in the keywords of a post. Note: current limitation, right now, if a term like "nights" appears 4 times in one post, and 2 times in another post, those are considered equal. 
3. The typeahead front end is the same. 
Once this lands, I'll create a new tag and push out a release
@akuhn as an FYI
=> [Search] Add keyword search + ranking

.gitattributes
@matthewwardrop @earthmancash @danfrankj 
2 minute fix that will hopefully stop the repo from being classified as a JS one based on the Linguist library that Github uses (https://github.com/github/linguist)
=> [Linguist] Fix language stats by excluding some js files

knowledge_repo/app/static/css/custom.css, knowledge_repo/app/templates/base.html
The title is pretty self explanatory - on the new typeahead search, there was a regression where if you pressed the down arrow, you saw `[object object]` in the search box, as opposed to the title, so I fixed that + added a background color on the mouse down so you could see which suggestion you were currently at. 
Test Plan:
Write in the search box and make sure a title shows up + background color exists when you use the arrow keys to scroll
@earthmancash @matthewwardrop @danfrankj
=> [Search] Show title on mouse down + add background color

knowledge_repo/_version.py, knowledge_repo/app/app.py, knowledge_repo/app/static/css/custom.css, knowledge_repo/app/templates/base.html
This was something we discussed earlier, and which I think looks classy.
Clicking `Knowledge Repo` takes you to this github repository. Clicking the version shows takes you to that version's release notes. Hovering over the version shows you the current git revision, if running out of a git repository.
@NiharikaRay @earthmancash @danfrankj
=> Show version of knowledge repo showing content.

knowledge_repo/converters/html.py
one of my favorite one-line changes... 
@matthewwardrop @NiharikaRay @earthmancash 
Markdown files that have a proxy key are rendered as proxy posts
=> added ability to have proxy posts

README.md
While waiting for the other Travis Build to finish, I decided to add these badges to the top of the README. 
@earthmancash @matthewwardrop @danfrankj
=> [README] Add badges of pypi + build

knowledge_repo/app/utils/render.py
In Python 2, `str.encode()` returns an encoded `str`ing object, while in Python
3, the same call returns a `bytes` object. This mismatch causes display issues
on the "View Raw Markdown" page. (H/T @b11z)
On `master`:
Post-PR:
=> Fix bytes encoding bug between Python 2 and 3

knowledge_repo/converters/rmd.py
Added small change to creating a new post from an `Rmd` based on issue [109](https://github.com/airbnb/knowledge-repo/issues/109). Errors currently get thrown on Windows as the use of `os.path.abspath()` creates file paths using `\` on Windows. `R` doesn't like `\` and needs to have it escaped. Without doing so, the first `R` call inside knowledge_repo/converters/rmd.py to `setwd()` fails. 
I've added a small check that will replace all `\` with `\\` in the `runcmd` variable to try and correct for this if the `os.name` value returns `nt` (Windows). 
Test Plan: 
=> Attempt minor fix for knit Rmd into knowledge repo if system is windows

knowledge_repo/app/index.py, knowledge_repo/app/routes/web_editor.py, knowledge_repo/app/templates/email_templates/review_email.txt, knowledge_repo/app/templates/email_templates/reviewer_request_email.txt, knowledge_repo/app/templates/post_editor.html, knowledge_repo/app/utils/emails.py, knowledge_repo/post.py, knowledge_repo/repositories/dbrepository.py, knowledge_repo/repositories/meta.py, knowledge_repo/repository.py, tests/test_emails.py, tests/test_webeditorposts.py
@matthewwardrop @NiharikaRay @earthmancash 
Refactor of webeditor flow including
* use current_repo rather than Post() models to retrieve and manipulate posts 
* allow users to specify which repo to submit a post to 
* various cleanup 
* security updates so you can't delete others posts / comments 
TODOs 
* a few cases where we do need the post id to retrieve comments, etc. 
* testing
=> refactor of webeditor code

knowledge_repo/app/app.py, knowledge_repo/app/deploy/__init__.py, knowledge_repo/app/deploy/common.py, knowledge_repo/app/deploy/flask.py, knowledge_repo/app/deploy/gunicorn.py, knowledge_repo/app/deploy/uwsgi.py, knowledge_repo/app/routes/index.py, scripts/knowledge_repo
This patch set improves the deployment process, in part based on work by @yolken. Where possible, it does not write out temporary files but instead just launches gunicorn from within-process. This is useful when trying to compile knowledge_repo into a standalone executable format (such as pex).
This solves #97.
=> Improve logic around deployment of the knowledge repo.

knowledge_repo/repositories/dbrepository.py
This fixes a couple issues I ran into when trying to run the knowledge repo over a postgres DB.  Without these changes, I wasn't able to get commands like `knowledge_repo add` to complete, and with them, I was.
=> Enable DBRepository to work with Postgres and fix a couple errors

knowledge_repo/app/index.py, knowledge_repo/repositories/dbrepository.py, knowledge_repo/repository.py
@matthewwardrop 
Previously current_repo.revisions returned a mapping from mountpoint to Repository object which can't be queried
=> bugfix to allow reindexing

knowledge_repo/app/app.py, knowledge_repo/app/index.py, knowledge_repo/app/templates/base.html, knowledge_repo/app/utils/time.py, knowledge_repo/repositories/dbrepository.py
In v0.7.1 there are some issues regarding checking the revision of DBKnowledgeRepository instances. Rather than force KnowledgeRepository instances to return string revisions, we now simply require them to return something that can be automatically converted to a string, and that is lexically ordered so that newer revisions sort lower than older ones.
There's also some small improvements to the base template to use glyphicons and to show the latest time an update check was performed (on hovering over the last time the index was updated).
=> Convert all revisions to strings before comparison, and some neatening up of index logic.

knowledge_repo/repositories/gitrepository.py
If your git repository is hosted on a different port than 22 you cannot connect to it using ssh.  This PR solves it by extracting the port number from the repository's URL. If no port is specified it defaults to 22. 
Test Plan: 
Testing regexp below, with and without a port number, without a port number it should return None, which the ___remote_port property would capture and in that case return 22.
```
git_remote_url = "ssh://git@some.domain.com:123/repo/project.git"
m = re.match(r'^(.*?)?@([^/:]*):?(\d+)?', git_remote_url)
print(m.group(3))
git_remote_url = "ssh://git@some.domain.com/repo/project.git"
m = re.match(r'^(.*?)?@([^/:]*):?(\d+)?', git_remote_url)
print(m.group(3))
git_remote_url = "https://git@some.domain.com/repo/project.git"
m = …
```
=> Support for different port numbers in git uris

knowledge_repo/post.py, knowledge_repo/postprocessors/extract_images.py, knowledge_repo/postprocessors/format_checks.py
This addresses #51 and the issues in the discussion of #115.
Thumbnails can be specified as integers (in which case the nth image is chosen as the thumbnail) or strings (in which case the string is treated as a url). The resulting url is then hard coded as the thumbnail header of the generated markdown file, which means that if this logic changes in the future, old posts will not be affected.
=> Add support for specifying a thumbnail image, and fix some bugs in the post caching mechanism.

scripts/knowledge_repo
* Let --help/-h fall through to where subcommands are defined so the
list of them can be seen
* Show abbreviated top-parser help when --repo is not set to retain a
hint of what the user needs to do
* Fix formatting of the ValueError
* Fix odd git interrupted errors, missing subprocess return code by
waiting for the subprocess to complete
* Fix case where no args are specified at all, show the help
=> Minor CLI improvements for help, exit codes

knowledge_repo/app/utils/render.py
This fixes encoding of forward slashes in paths, which breaks the rendering of linked paths. This is a temporary measure, since the url revamp will change how paths are encoded in urls.
This fixes #78 .
=> Add temporary fix before url revamp makes this redundant.

knowledge_repo/app/routes/tags.py
This one character fix gets /batch_tags up and running again:
Test Plan: 
ran the route locally
=> excluded tags typo fixes batch tags

knowledge_repo/app/templates/base.html
This fixes search when searching from viewing a post or in any other endpoint besides /feed. 
Test Plan: 
Searched from a post view
=> Always use /feed when searching from searchbar

knowledge_repo/app/app.py, knowledge_repo/app/index.py, knowledge_repo/app/routes/__init__.py, knowledge_repo/app/routes/debug.py, resources/extract_images_to_s3.py, scripts/knowledge_repo
This patch set fixes a few small reindexing bugs, and adds some debug routes to assist in future problems like this one. In particular it addresses the following:
- If a reindex has taken longer than 10 minutes, new reindexes are now allowed to occur; preventing a failed reindex / crashed server from preventing the index from being up to date.
- A manual reindex can now be forced using the `reindex` action in the `knowledge_repo` script or (when running in debug mode) the `/debug/force_reindex` route.
- Fix a small bug when chaining script and wanting to return the nested script's error code.
- Fix S3 upload sample script for Python 3.
- Add a debug route `/debug/versions` that shows the versions of both system and installed packages that are pertinent to the knowledge repository (see …
=> Small cleanups to indexing, along with some extra debugging tools.

README.md
Quick documentation for post headers. The README is getting to a point where we may need a full site for documentation, but let's get this stuff down for now.
PTAL @NiharikaRay @matthewwardrop @danfrankj 
Test Plan: 
=> Add section in documentation for post headers

knowledge_repo/app/templates/about.html, knowledge_repo/templates/repo_data_readme.md
Unfortunately right now we have three different places for documentation:
- repo's README
- readme stub that's copied to data repos
- about.html
This PR does the change from https://github.com/airbnb/knowledge-repo/pull/173 into the latter two sources. 
Test Plan: 
=> spread post header documentation to other documentation areas

knowledge_repo/_version.py
This fixes the travis build and client installs.
=> Fix jupyer_client.manager being missing due to upstream changes in nbconvert (explicitly depend on required functionality).

README.md
The $ is appropriate when accessing the variable (e.g., echo $KNOWLEDGE_REPO), but when setting the variable's value, omit the $. For instance: export KNOWLEDGE_REPO=/Users/me/git/my-file-path
=> Omit $ when setting variable value

knowledge_repo/repositories/dbrepository.py
This addresses issue #155, which was causing issues not to show up in knowledge posts when using a database repository.  The change fixes the `_kp_dir` method of `DbKnowledgeRepository` to look for the parent arg in the `ref` column of the database.
Test Plan:
Without this change, images didn't display in my knowledge posts.  With the change, they did.
=> In DbKnowledgeRepository, better handling of parent arg in _kp_dir

knowledge_repo/repositories/dbrepository.py
Currently MySQL times out after about 8 hours (by default), but the DBKnowledgeRepository does not know this and attempts to connect to the db; resulting in a crash. This patch should cause MySQL connections to be recycled every hour or so; preventing this from happening again.
Test Plan: 
=> Fix the DBKnowledgeRepository MySQL timeout errors

knowledge_repo/app/templates/post_editor_base.html
Once a user has saved the path, the APIs that will be called by UI buttons are hardcoded. This change makes it so that once the path is set it becomes uneditable.
=> when editing a specific path, the path should not be editable

knowledge_repo/app/routes/render.py, knowledge_repo/app/templates/markdown-base.html
Description of changeset: If you're the author of the webpost, you now get a button on top of the rendered post to quickly take you to the webeditor
Test Plan: 
1. Create a webpost where you're the author, publish it, and ensure you see the button (and the button can be clicked to take you to the webpost)
2. Create a webpost where you're not the author, and ensure the button doesn't show up. 
Auto-reviewers:  @matthewwardrop @earthmancash @danfrankj
=> [KR] Add easy link to webeditor

knowledge_repo/post.py
headers are being written twice since the regex looks for a newline. It seemed safer to take out the headers before writing when updating headers so that we don't have to rely on the regex
=> fix double writing of metadata

knowledge_repo/app/migrations/alembic.ini, knowledge_repo/app/models.py, run_tests.sh
This patch makes three small improvements:
- Sets Alembic logging to WARN, rather than INFO. This makes the testing output a lot cleaner, and we do not lose any useful information in the process.
- Sets nosetests verbosity to 1 (the default). The names of tests are not generically useful unless something goes wrong (where it is then displayed in detail).
- Added a small fix to pre-empt a null result in the favourited posts query for a given user (and hence suppress an SQLAlchemy warning).
Running the tests is now much less verbose, and it is more obvious when something actually goes wrong. You can verify this using:
```
./run_tests.sh
```
=> Testing verbosity improvements

knowledge_repo/app/routes/web_editor.py
Quick Templating solution for webeditor created posts 
By passing in urlparams, we can create templates for users. Obviously, this feature will need to be used in conjunction with an external url shortener.
http://0.0.0.0:7777/posteditor?markdown=%23%20%28GitHub-Flavored%29%20Markdown%20Editor%0A%0ABasic%20useful%20feature%20list%3A%0A%0A%20%2A%20Ctrl%2BS%20/%20Cmd%2BS%20to%20save%20the%20file%0A%20%2A%20Ctrl%2BShift%2BS%20/%20Cmd%2BShift%2BS%20to%20choose%20to%20save%20as%20Markdown%20or%20HTML%0A%20%2A%20Drag%20and%20drop%20a%20file%20into%20here%20to%20load%20it%0A%20%2A%20File%20contents%20are%20saved%20in%20the%20URL%20so%20you%20can%20share%20files%0A%0A%0AI%27m%20no%20good%20at%20writing%20sample%20/%20filler%20text%2C%20so%20go%20write%20something%20yourself.%0A%0ALook%2C%20a%20lis …
=> pass in urlparams to the webeditor form so that users can create their own templates via urlshorteners

knowledge_repo/app/app.py, knowledge_repo/app/routes/__init__.py, knowledge_repo/app/routes/editor.py, knowledge_repo/app/routes/index.py, knowledge_repo/app/static/js/tooltips.js, knowledge_repo/app/templates/create-knowledge.html, knowledge_repo/app/templates/markdown-base.html, knowledge_repo/app/templates/post_editor_base.html, knowledge_repo/app/templates/web_posts.html, knowledge_repo/app/utils/emails.py, tests/test_webeditorposts.py
This post updates the urls used by the web editor, which is now moved from `/post_editor?path=<path>` to `/edit/<path>`. Ajax queries are now moved under to the `/ajax/editor` and `/ajax/index` prefixes as appropriate. This patch does not attempt to fix any issues with the editor itself, but simply updates the url schema.
=> Update urls for the online editor.

knowledge_repo/app/utils/render.py, knowledge_repo/postprocessors/format_checks.py
Allow the TLDR to be unicode and fix formatting the header causing unicode errors. Also add markdown extension allowing github style md. 
@matthewwardrop @NiharikaRay @earthmancash
=> support unicode in tldr and add markdown newline extension

knowledge_repo/app/static/js/tags.js
A 6 character change. With the complexity of the post javascript, the url that the subscribe button was going to was `post/<post_path>/toggle_tag_subscription`, which was throwing a 405, method not allowed error (since we only GET posts, not POST). This PR ensures that its `/toggle_tag_subscription` that gets the ajax request. 
Test Plan: 
Go to a post and subscribe to a tag from it. 
Auto-reviewers: @matthewwardrop @earthmancash @danfrankj
=> [Knowledge][Bugfix] Allow tag subscription from rendered post

.gitignore
git ignore .DS_Store used in Mac OS filesystems.
Test Plan: 
nothing
=> git ignore .DS_Store

.travis.yml
we now have a `deploy` directory which included templatized `.py` files that violates python syntax when parsed directly. this PR excludes the directory to prevent those files from being style-checked so we could get a green build.
Test Plan: 
tested on travis.
=> exclude deploy directory for checking styles

.travis.yml, run_tests.sh
we are adding another directory `kube` to the internal repo which requires style checks to be skipped due to templatized python files.
=> exclude kube directory from style checks

knowledge_repo/post.py
If a knowledge post is not processed by the ExtractImages PostProcessor, or manually edited, the thumbnail uri might not be in a supported format. This patch adds a check to ensure that the thumbnail header is understood before attempting to use it (in particular, that it is a string; and not an integer or other type).
=> Fix KnowledgePost.thumbnail_uri when not header not processed by ExtractImages for whatever reason.

knowledge_repo/app/models.py, knowledge_repo/app/templates/markdown-rendered.html
Description of changeset: This is related to issue #214, where the date wasn't showing up in the comments. This PR changes that. 
Test Plan: 
Write a comment, note that the date now shows up in the rendered comment box.
=> [Knowledge] Add date formatting to comments

knowledge_repo/app/static/css/custom.css, knowledge_repo/app/static/css/pages/index-feed.css, knowledge_repo/app/static/js/pages/index-feed.js, knowledge_repo/app/templates/index-feed.html, tests/test_feed.py
This patch set improves the rendering of the knowledge post index feed by:
- Making rows more compact and with more consistent heights (descriptions are collapsed)
- Visual feedback for interaction (backgrounds on hover, depression when clicked)
- Making the who row clickable to take you to the post proper
The new javascript methods are encapsulated in a closure so that they do not clutter the global namespace, and both the javascript and css files are loaded only on the page they are required.
Below are some screenshots of the new theming:
=> Improve feed rendering.

knowledge_repo/app/routes/posts.py
Description of changeset: Thanks dsimmie for reporting! https://github.com/airbnb/knowledge-repo/issues/217
The `raw` variable wasn't defined, so previewing posts was broken. This PR should fix the issue, by getting the raw variable from the request.args, similar to how is done in the render route.
Test Plan: 
Preview a post, make sure it works.
=> [Bugfix] Make sure raw preview works

knowledge_repo/app/app.py, knowledge_repo/app/static/css/custom.css, knowledge_repo/app/static/css/pages/index-feed.css, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/templates/index-feed.html, knowledge_repo/app/utils/posts.py
This changeset improves the styling of the feed page by adjusting margins along with a new set of pagination controls, along with another pagination bar at the bottom of the page. The pagination controls disappear if there is only one page. The code also removes the need for custom javascript on the page, and fixes a small oversight in the css for the feed hover css (the thumbnail border was not transitioning properly).
=> Improve the pagination controls.

knowledge_repo/app/deploy/__init__.py, scripts/knowledge_repo
This fixes two related issues:
- The `create` action in the knowledge_repo script did not terminate upon succeeding, allowing subsequent code to run, which included importing of the deployment code. On the the Windows platform, this resulted in an error importing gunicorn (gunicorn does not support non UNIX platforms).
- A hard import of GunicornDeployer would, on Windows platforms, make it impossible to "deploy" the server. I do not imagine Windows servers being used often in this capacity, but it is worth preventing this spurious behaviour.
=> Fix Windows deployment related code

knowledge_repo/converters/rmd.py, run_tests.bat
Fix Rmd conversion in Windows, which is currently failing due to stricter simultaneous write permissions on Windows than POSIX systems.
=> Fix Rmd conversion in Windows.

knowledge_repo/app/routes/posts.py
I just realised the javascript wasn't executing properly in preview mode (so the code folding didn't work while previewing). It is due to the var tags_list being rendered as a list but with no brackets '[' and ']' around it; removing the ','.join method casts it as a list instead of a string and fixes it. 
Test Plan: 
1. Run an instance of the knowledge repo
2. Preview any post and verify that no errors were raised in the javacript console
=> Fix malformated tags_list breaking javascript in post preview mode

knowledge_repo/app/migrations/versions/9715822acf6c_add_errorlog_table.py, knowledge_repo/app/models.py
This patch-set adds a separate error log table instead of combining error logs with the pageviews table. This will be used in my next PR to store index updating errors also; and can be used by other internal functions in the future.
In the migration, past error logs are dropped. I don't foresee this being an issue... but if necessary, we can fix the migration to conserve historical error logs. My take is that these logs are not worth maintaining, and will lead to incomplete error logs being stored in the error log table (due to us now collecting more information when errors occur).
=> Add new table for storing error logs, as distinct from pageviews.

knowledge_repo/app/static/css/custom.css, knowledge_repo/app/templates/markdown-rendered.html
Currently id based styling takes precedence over class based styling preventing the user from overwriting it inline.  With this change we can now use pandas.DataFrame.style (although I'm currently hacking around this bug https://github.com/pandas-dev/pandas/issues/15651)
@matthewwardrop @NiharikaRay
=> make markdownRendered a class so that style can be overwritten

knowledge_repo/app/routes/posts.py
Also do we still need to have implicit groups 
@NiharikaRay @matthewwardrop 
```
group = Group(name=":post_group_" + str(self.id))
```
=> allow author to see posts even if they are private

knowledge_repo/app/static/js/pages/index-feed.js
Unfortunately, since the HTML5 specification prohibits nested anchor tags, we cannot have the panel be a link it self without using javascript (unless we forgo the ability to click on authors/etc). To work around this, I add in this PR support for detecting the appropriate modifier keys and opening in a new tab accordingly.
=> Add support for modifier keys when click on post panels

knowledge_repo/app/app.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/static/css/pages/base.css, knowledge_repo/app/static/css/pages/index-feed.css, knowledge_repo/app/static/css/pages/markdown-base.css, knowledge_repo/app/static/js/pages/base.js, knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/templates/markdown-base.html, knowledge_repo/app/templates/markdown-presentation.html, knowledge_repo/app/templates/markdown-raw.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/stats.html, knowledge_repo/app/utils/emails.py, knowledge_repo/app/utils/render.py, knowledge_repo/converters/html.py, knowledge_repo/converters/pkp.py, setup.py
This patch set brings some much-needed love to the user interface to the knowledge repo, addessing #45, #257, #287 and #291 . In particular, it:
- Improves the appearance of the top bar, and makes it fixed and always available.
- Makes the entire interface responsive (you will need to play around with resizing windows to see the full benefit of this work)
- Added support for responsive side-bars
- Posts are now rendered with an interactive table of contents and with download links (which are also responsive)
- Table theming is greatly improved, are rendered as centered and gracefully scroll when overflowed (based on the table styling used in Jupyter)
- Post title is used for window/tab/page title.
- Many other smaller user interface tweaks.
As part of this work, support was added for …
=> Improvements to the Knowledge Repo UI

scripts/knowledge_repo
This very simple PR is adding quotes to the post creation message. This prevents the terminal emulator's smart selection to select the final period. I used single quote to match the style of other messages in the CLI interface.
Test Plan: 
Modified locally and it did what I expected. 
=> [CLI] add quotes to message to enable easier path selection

knowledge_repo/post.py, tests/test_posts/numerical_tags.ipynb
Fixes site breaking when numerical tags are present (fixes #294).
=> Automatically promote numerical tags to strings.

knowledge_repo/postprocessors/extract_images.py
In Windows, reference paths should still be indicated using posix/html-like path separators, otherwise images break for posts generated on Windows. This simple patch resolves this for all *new* posts. (This supersedes that #302 that added a hack later in the post rendering pipeline, and which could on occasion break urls containing `\`).
@zerogjoe @susanjo80: Can you verify that this resolves these issues for you?
=> Fix reference path in Windows.

README.md, knowledge_repo/app/routes/posts.py, knowledge_repo/post.py, knowledge_repo/templates/repo_data_readme.md
With the current workflow, users are not supposed to directly modify the markdown, and so we expect that the source code should be in sync with the rendered format. This tight coupling will continue to strengthen in upcoming versions (with new tooling), so to avoid confusion, we here rename `orig_src` to `src` inside of posts. This patch maintains legacy accessing of `orig_src` paths for now.
=> Update source paths from `orig_src` to `src`.

knowledge_repo/app/app.py, knowledge_repo/app/auth_provider.py, knowledge_repo/app/config_defaults.py, knowledge_repo/app/utils/auth.py
Currently, only `AuthProvider` instances can set user attributes. It is often necessary, however, for servers managing user authentication using request headers to assign user attributes also. This patch, has been tested locally, furnishes this functionality.
=> Allow the knowledge_repo server to populate various user attributes (if desired)

knowledge_repo/app/app.py, knowledge_repo/app/config_defaults.py, knowledge_repo/app/deploy/flask.py, knowledge_repo/app/deploy/gunicorn.py, knowledge_repo/app/deploy/uwsgi.py, knowledge_repo/app/index.py, knowledge_repo/app/models.py, knowledge_repo/app/routes/debug.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/utils/time.py, scripts/knowledge_repo
... and making use of improved error logging.
This patch reworks how index synchronisation is done. Previously, every thread would attempt to trigger an update to the index (if needed) at request time. This patch changes this behaviour such that one instance/thread of the knowledge repo claims to be the index master, and remains so until it fails to update the index; whereupon this responsibility automatically shifts to a difference instance. This should greatly reduce the chance of lock collisions.
As a result of this improved logic, we can now update the knowledge repositories as part of the index update, for which initial support is added in this PR. This will likely be improved on the actual post storage side in the future, to enable, for example, tunnelled git operations for updating …
=> Improve indexing by separating timing into separate thread

README.md
Fixed small typo in README (example in `Post Headers` section) 
=> Fix typo in Post Headers examples

knowledge_repo/converters/rmd.py
Tested adding a Rmd file that required some init code found in Rprofile 
Addresses
https://github.com/airbnb/knowledge-repo/issues/334
@matthewwardrop
=> R converter should not skip init files 

README.md, scripts/knowledge_repo
I added an optional `--template` parameter when creating a knowledge post. This allows users to specify their own template instead of using the prebuilt defaults, which can be verbose. I updated the documentation to reflect these changes.
Fixes #339 
Test Plan: 
There were no tests for CLI parsing in the current repo, but I confirmed that existing tests pass.
=> Added optional --template parameter when creating knowledge post

README.md
This looks like an awesome project! This PR is for a small typo fix. Since [IPython](http://ipython.org/index.html) stands for "Interactive Python" and is not an apple product, the correct abbreviation is IPython not with a lowercase "i."
Looking forward to trying it out!
- Fix "iPython" --> "IPython"
Test Plan: 
- None
=> iPython --> IPython

knowledge_repo/converters/html.py
Addresses https://github.com/airbnb/knowledge-repo/issues/350
By using string replacement instead of regex substitution post rendering went from ~5 seconds to ~.1 seconds 
@matthewwardrop
=> update urlmapper to use string replacement for speed

knowledge_repo/app/routes/index.py
Currently the post search typeahead shows any posts, this change makes it so typeahead only shows published posts. 
@NiharikaRay @robjwang
=> restrict typeahead search to only show published posts

knowledge_repo/app/app.py, knowledge_repo/app/templates/permission_denied.html
This PR creates a new template for use when a user attempts to view a page they are not authorized to see without logging in.  (Addresses #366) If the user is not signed in, they are prompted to sign in and try again.  If they are already signed in, it displays a less helpful "contact an admin" message.
Screenshot of new template:
=> Add template for permission denied

knowledge_repo/app/auth_providers/oauth2.py, knowledge_repo/app/config_defaults.py, resources/server_config.py
The purpose of this PR is to simplify the process of supporting a generic OAuth2 authentication provider when deploying the software, and also to support self-signed CAs for those authentication providers.
- Added a `verify_https` parameter to the `OAuth2Provider` class, whose only purpose is to be passed to the Requests module as the `verify` parameter. This is to support custom CAs (or disabling HTTPS verification entirely)
- Added a generic empty `OAuth2Provider` preset called `oauth2`, the purpose of which is to be overridden by the server administrator in server_config.py.
- Added examples of the use of both of these to `config_defaults.py`
- Synced `resources/server_config.py` with `config_defaults.py` as this is the config template referred to in the …
=> Enable generic OAuth2 config and support self-signed provider CAs

docs/quickstart.rst
In the example submission, I believe `knowledge_repo preview` is used when `knowledge_repo submit` is correct.
Test Plan: 
=> Change `preview` to `submit`

knowledge_repo/config_defaults.py, knowledge_repo/config_defaults.yml, knowledge_repo/repositories/gitrepository.py, knowledge_repo/utils/git.py, run_tests.bat, run_tests.sh, scripts/knowledge_repo
This is a follow up to #382 , which removed one method that a malicious user could use to cause arbitrary code to be run on client and server machines. This mitigates a second method, which was the running of arbitrary code within a git submodule in GitKnowledgeRepository instances when tooling was embedded.
This PR removes any dependence on git submodules, but retains the ability to pin `knowledge_repo` versions, since embedded tooling is still useful to help admins narrow the variance of user experiences (everyone will be using exactly the same `knowledge_repo` version). To cause arbitrary code to be run after this patch is merged, a malicious user would need to compromise network routing and perform a man-in-the-middle-attack, or hack this upstream repository, neither of which seems …
=> Remove unsafe tooling embedding, and replace with much safer method of pinning tooling version.

knowledge_repo/app/app.py, scripts/knowledge_repo
**Description of changeset:** 
In addition to having an upgrade function for databases, it is nice to have a downgrade one (which I found was necessary when testing the permission changes)
**Test Plan:** 
Run the command, both with supplying a revision number and not, and expect it to run - it fails on sqlite databases due to the lack of alter column support
Also, made a slight change to the PR template, after dogfooding it
Auto-reviewers:  @matthewwardrop @earthmancash @danfrankj
=> Add downgrade actions to dbs

knowledge_repo/converters/rmd.py
The Windows build has been broken for a while. It looks like `R -e "..."` no longer supports spaces on Windows. We therefore use `Rscript` instead which is designed for this purpose, and works on all operating systems.
=> Fix Windows build.

knowledge_repo/app/app.py, knowledge_repo/app/config_defaults.py
This PR adds support for setting user attributes using auth headers.
Build errors are due to a fussier pycodestyle 2.4.0 . Will fix in a separate push.
=> Add more complete support for header auth.

knowledge_repo/app/routes/posts.py
This allows to change how the comment author name is displayed.
Currently, when logging in with Google, the comment author is displayed as the email address.
I would like to display the name of the commenter instead of his email address.
Here is a screenshot of the output.
Test Plan: 
I am not sure how/if the comment list is tested. 
=> Allow to customize comments display

knowledge_repo/app/templates/base.html
Super simple PR to add a meta tag to the base template to make KR play nice with mobile esp Android devices:
=> Adding a meta tag for Knowledge Repo mobile layout changes

knowledge_repo/app/deploy/gunicorn.py
This PR mimics logic [here](https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L150) to allow additional Gunicorn configuration to be defined via the `GUNICORN_CMD_ARGS` environment variable, i.e., 
```
GUNICORN_CMD_ARGS='--statsd-host=localhost:8125' knowledge_repo deploy
```
Test Plan: 
Verified that the command line args where present.
=> [gunicorn] Adding environment configuration

knowledge_repo/app/routes/index.py, knowledge_repo/app/static/css/pages/base.css, knowledge_repo/app/static/js/index-cluster.js, knowledge_repo/app/templates/index-cluster.html
This PR adds a nested structure to the /cluster view, allowing for more compact categorization of posts. It is intended to resolve issue #170 
Sample screenshot:
Very happy to take suggestions on how to properly test this. Also feedback on the javascript changes are particularly welcome as I'm a bit of a novice.
=> Nested folder structure for cluster view

knowledge_repo/repositories/gitrepository.py
Fixes #448
`master` branch was hardcoded instead of using the provided one.
**Description of changeset:** 
A single line in `knowledge_repo/repositories/gitrepository.py` has been modified to use the correct branch.
**Test Plan:** 
- `gitrepository.py` is not currently being unitary-tested, so I did not add a test for it.
- After the patch is added, execute the steps in #448 to verify it is working.
=> Fix git reindexing using custom branch

.travis.yml, appveyor.yml, tests/config_server.py
Travis scripts were not actually using the Python versions specified in the build matrix (`conda` was installing 3.7 for the Python 3 build).
Test Plan: 
Run CI
=> Configure Travis tests for Python versions

knowledge_repo/_version.py, knowledge_repo/app/migrations/versions/d15f6cac07e1_add_subtitle_field_to_post_database.py, knowledge_repo/app/models.py, knowledge_repo/app/static/css/pages/base.css, knowledge_repo/app/static/css/pages/markdown-base.css, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/utils/render.py, knowledge_repo/converter.py, knowledge_repo/converters/ipynb.py, knowledge_repo/converters/md.py, knowledge_repo/converters/pkp.py, knowledge_repo/converters/rmd.py, knowledge_repo/post.py, knowledge_repo/postprocessors/format_checks.py
This patch-set improves the functionality around headers and their presentation.
In particular:
=> Add subtitle field and allow interactive specification of headers.

knowledge_repo/config.py, knowledge_repo/converters/pkp.py, knowledge_repo/repositories/folder.py, knowledge_repo/repositories/gitrepository.py, knowledge_repo/repository.py, run_tests.bat, run_tests.sh, scripts/kp, setup.py
This PR begins work on improving the user experience when working with knowledge posts. This PR utilises the portable knowledge posts introduced in earlier work to act as the repository-independent representation of knowledge post that can the be added to one or more repositories at whim.
The `FolderKnowledgeRepository` is used for previews of knowledge posts that can now be located anywhere on your hard drive. Unless explicitly requested by referencing the repository using the `file://` protocol, it will automatically be replaced by a `GitKnowledgeRepository` if a '.git' folder is found within it, ensuring backwards compatibility.
In the future we can extend this new tooling with such functionality as `edit` and `create`.
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash …
=> Improve tooling and backend for creating and working with knowledge posts

knowledge_repo/converter.py, knowledge_repo/converters/docx.py, knowledge_repo/converters/gdoc.py, knowledge_repo/converters/proxy.py
This PR adds better support for Google Docs and Slides by:
=> Better support for Google Docs

knowledge_repo/_version.py, knowledge_repo/post.py
Currently, when thumbnails are too large, the base64 encoded string representing the image can exceed the typical limit of 65535 characters on the thumbnail field in the model. This patch fixes this by explicitly resizing the thumbnail on index generation.
=> Add explicit thumbnail resizing for thumbnails.

knowledge_repo/app/app.py, knowledge_repo/app/deploy/common.py, knowledge_repo/app/deploy/flask.py, knowledge_repo/app/deploy/gunicorn.py
The current implementation of multi-threaded indexing is triggered at instance creation time, instead of deployment time, breaking some of the useful utilities in the `knowledge_repo` script including forcing a reindex. This patch defers index initialisation until deployment.
=> Delay starting indexing until actually deploying server.

knowledge_repo/app/utils/posts.py
I believe this could resolve https://github.com/airbnb/knowledge-repo/issues/363
The issue is that `index-table.html` uses these column names when forming the `sort_by` query parameter ...
```
var col_names = ['Title', 'Author', 'CreatedAt', 'UpdatedAt', 'Views', 'Upvotes', 'Comments']
```
... but `posts.py` is expecting sort_by columns like ...
```
post_properties = {
"updated_at": Post.updated_at,
"created_at": Post.created_at,
"title": Post.title,
}
join_order_col = {
"uniqueviews": func.count(distinct(PageView.user_id)),
"allviews": func.count(PageView.object_id),
"upvotes": func.count(Vote.object_id),
"comments": func.count(Comment.post_id)
}
```
`views` isn't among the options but `uniqueviews` and `allviews` are. I think this should be an alias for …
=> Fix sorting by 'views' column in Table view

knowledge_repo/app/templates/stats.html
Subtract 1 from months when making JavaScript Dates for use in Google charts. JS months are 0-indexed.
I believe this resolves https://github.com/airbnb/knowledge-repo/issues/278
This seems to be the jinja2 way of subtracting from a variable's value:
http://jinja.pocoo.org/docs/2.10/templates/#math
Test Plan: 
`./run-tests.sh` passes. I admit I'm not sure how to run the locally built copy of knowledge repo to check the change.
=> Subtract 1 from months when making JavaScript Dates for use in Google charts

docs/deployment.rst
Add note about setting up Github authentication with ssh.
This is intended to document the suggestion in https://github.com/airbnb/knowledge-repo/issues/428 and this has worked for me. 
Test Plan: 
Built and checked the docs.
=> Add note about setting up Github authentication with ssh

docs/deployment.rst, docs/quickstart.rst, docs/workflows/writing.rst
Clarify DB URI docs, and fix display of --flags that render as -flags in docs (em-dash).
I believe this is what https://github.com/airbnb/knowledge-repo/issues/423 was requesting for doc updates. I added a note about sqlite URIs as that worked for us.
Separately I also fixed a small issue, that sphinx seems to collapse `--` to an em-dash for flags like `--dburi` in the docs, which makes them incorrect as `-dburi`. That also tripped me up for a second.
(There are many instances where code-like text is back-ticked and actually renders as italics, but I didn't bother with those.)
Test Plan: 
Manually built docs and verified.
=> Clarify DB URI docs, and fix display of --flags that render as -flags in docs (em-dash)

docs/workflows/writing.rst
Description of changeset: Updated the documentation for updating a post by adding the `-p` parameter because running as specified in documentation throws `knowledge_repo: error: unrecognized arguments:`
Test Plan: 
=> Added -p parameter to update documentation

knowledge_repo/app/templates/index-base.html
The "Cluster" button isn't receiving the same margin between lable and icon as "Card" and "Table".
Test Plan: 
=> Fix typo "nane"->"name"

docs/deployment.rst
Added explanation on how init does not create a git repo by default and how to create one by prefixing git:/// to the desired repo path. See issue #482 for more information.
Test Plan: 
=> Added explanation how init creates git repo #482

knowledge_repo/app/migrations/alembic.ini, knowledge_repo/app/migrations/versions/eb39ac93fc39_add_pageview_indexes.py, knowledge_repo/app/models.py
Addes indexes to speed up queries that take >90% of the load time for the homepage
Test Plan: 
CI and tested in Airbnb's environment
@john-bodley @serenajiang @danfrankj
=> Add pageview indexes

knowledge_repo/app/migrations/versions/009eafe4838f_add_support_for_external_authentication.py, knowledge_repo/app/migrations/versions/1b385158fd32_assoc_rename_and_uuid_column.py, knowledge_repo/app/migrations/versions/36baffc5df12_add_groups_permissions_to_posts.py, knowledge_repo/app/migrations/versions/38eeba774226_resize_email_text.py, knowledge_repo/app/migrations/versions/9715822acf6c_add_errorlog_table.py, knowledge_repo/app/models.py, knowledge_repo/utils/types.py
Currently the email body is defined as a `TEXT` field which for MySQL is limited to ~ 64 KB. This is problematic as the body includes the embedded images from the post and if they're too large can result in a blocking MySQL error which prevents the repo from being reindexed. 
This PR changes the schema of the `emails.text` column to be `MEDIUMTEXT` (~ 16 MB) for MySQL instances.
Test Plan: 
Ran `knowledge_repo --repo={} --dev db_upgrade` locally using both MySQL and SQLite and verified the schema.
to: @etr2460 @NiharikaRay
=> [schema] Increasing email body size

.gitignore
Removing erroneous `tests/test_repo` introduced accidentally in  https://github.com/airbnb/knowledge-repo/pull/537 which is a byproduct of running the `run_tests.sh` script.
Test Plan: 
CI.
to: @etr2460
=> [fix] Removing tests/test_repo

knowledge_repo/_version.py, knowledge_repo/app/templates/email_templates/subscription_email.html, knowledge_repo/app/templates/email_templates/subscription_email.txt, knowledge_repo/app/utils/emails.py, tests/test_emails.py
Change subscription emails to contain a summary of the post instead of the entire post. This should fix some recurring issues for reindexing.
Mostly using @jihonrado's changes from #517 + fixing up some issues with the thumbnail image.
Tested on staging env. Received this email.
@etr2460 @john-bodley
=> Improve subscription emails (revised)

knowledge_repo/app/index.py
This PR ensures that if we're forcing a reindex this should occur regardless of whether the index is deemed up to date. This ensures that the index is updated whenever a force reindex occurs.
Test Plan: 
Tested locally via the CLI reindex command.
to: @etr2460 
cc: @NiharikaRay
=> [index] Ensure force reindexing occurs regardless of if the index is up to date

knowledge_repo/app/config_defaults.py, knowledge_repo/app/permissions.py, knowledge_repo/app/roles.py, knowledge_repo/app/routes/tags.py, knowledge_repo/app/utils/auth.py
Potential fix for #493. 
This change creates a new policy for viewing /tag_pages anonymously, and changes the permissions required to view /tag_pages from post_comment to tags_view.
Test Plan: 
I didn't see any existing tests around policies/roles/permissions, so I just confirmed that the existing test suite still passes with these changes.
=> Add policy for viewing tag pages anonymously

knowledge_repo/config_defaults.py
Tried to use this method to enforce consistency in usernames but it has a bug -- seems like in general this functionality is somewhat deprecated but as long as it is still around, might as well raise the correct error!
=> bugfix to the username_parse method

knowledge_repo/app/config_defaults.py, knowledge_repo/app/routes/posts.py, knowledge_repo/app/templates/markdown-rendered.html
Description of changeset: Configuration option to collapse all code in notebook as default display option for a knowledge post.
Test Plan: 
=> Collapse Code as Default Display Option

knowledge_repo/app/routes/comment.py
Fix #431, fix #254 
Enter the following in a post comment:
```
<script>alert("Client side attacks is possible here!");</script>
```
=> Fix XSS vulnerability by escaping comments

knowledge_repo/app/templates/markdown-presentation.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/post_editor_base.html
MathJax is not available from the CDN URL due to https://github.com/mathjax/MathJax/issues/2450#issuecomment-639074282
=> Fix MathJax CDN URL

knowledge_repo/app/config_defaults.py
Description of changeset: add DATABASE_URI for mysql defined as `SQLALCHEMY_DATABASE_URI = 'mysql://username:password@hostname/database'`.
Test Plan: I've tested on my local and production env with auto create tables from database defined on the URI which indicates as worked.
=> add default config for mysql database

knowledge_repo/_version.py
Simple fix to optional dependency information that fixes #578. `nbconvert` >= 6.0.0 do not include markdown.tpl (at least not in the expected place).
Test Plan: 
None.
=> Fixes #578

knowledge_repo/app/models.py
This PR fixes a regression introduced in https://github.com/airbnb/knowledge-repo/pull/547 where not all `raise_with_traceback` calls were updated. 
Test Plan: 
Mimicked the behavior outlined in https://github.com/airbnb/knowledge-repo/pull/547.
=> [models] Fix regression introduced in #547

knowledge_repo/app/models.py, knowledge_repo/utils/encoding.py
Description of changeset:  
`with_traceback` requires a traceback argument, but we're missing it.
```
builtins:TypeError: with_traceback() takes exactly one argument (0 given)
```
Updated usages of `with_traceback` to pass in the traceback. Based off example [in python docs](https://docs.python.org/3/library/exceptions.html#BaseException.with_traceback).
This is basically a duplicate of #584, but up-to-date with master.
Test Plan: 
Tested in python shell.
@john-bodley @etr2460
=> fix with_traceback calls

knowledge_repo/post.py
#547 had switched from `yaml.load_all` to `yaml.safe_load_all` because vanilla `load_all` is no longer recommended. This new behavior caused a few of our existing posts. The behavior of `yaml.full_load_all` seems more similar to the previous behavior, so this PR switches to using that function.
Deployed changes, confirmed that this fixed the broken posts
cc:
@bulam @naoyak
=> [fix] yaml safe_load -> full_load

knowledge_repo/app/auth_provider.py, knowledge_repo/app/routes/auth.py
This pull request fixes #594. 
Description of changeset: Changed the naming scheme for `auth_provider` blueprints.
Test Plan: It seems like the test suite is broken, but in testing this appears to fix the issue.
=> Don't use a dot delimiter for naming auth_provider blueprints

knowledge_repo/postprocessors/extract_images.py
When adding an ipython notebook, a postprocessor scans for images in the JSON by searching with a regex for markdown-style images like `[tag](url)`. The regex is as you see below. 
I had a cell with some inline Javascript like: `![123]...lots of stuff...](...stuff...)`. This matched as an image because the reluctant quantifier still forces it to expand the match of the tag until it sees "](". It shouldn't match.
The current regex looks for "space, or not space" in between the square braces. That didn't sound right -- why not "."? But in any event my guess is the intent is to match "anything except a closing square brace".
This at least made my case work. Submitted for your consideration.
=> Adjust regex matching markdown images to less eagerly match beyond the tag in brackets

docs/installation.rst
Add the instructions for handling of occupied 7000 port number with Mac OS.
Test Plan: 
CI
=> Update installation.rst for occupied 7000 port number on Mac

.travis.yml, knowledge_repo/repository.py
There are many lint errors related to long code lines, which have been addressed by reformatting.
Test Plan: 
CI
Reviewers:
@JJJ000
=> Reformat some long lines to avoid lint errors

.github/workflows/main.yml, .github/workflows/publish-to-test-pypi.yml
1. add task name to main workflow
2. add Build and publish workflow to pypi
by following: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
Test Plan: 
[x] verfiy on with test Test PyPI
@csharplus @etr2460
=> add package build and publish workflow

knowledge_repo/app/templates/auth-switcher.html
The links inside /auth/login are broken at least when using Python 3.10
Test Plan: 
Enter into the page  /auth/login with Google Auth enabled.
The links are now working and the icons are not broken
=> fix: Login authentication links were broken

docker/config.py, knowledge_repo/_version.py
A working example `app.py` for email integration is provided based on [SendGrid](https://sendgrid.com/blog/sending-emails-from-python-flask-applications-with-twilio-sendgrid/), as listed below:
```
from flask import Flask
from flask_mail import Mail, Message
app = Flask(__name__)
app.config["SECRET_KEY"] = "top-secret!"
app.config["MAIL_SERVER"] = "smtp.sendgrid.net"
app.config["MAIL_PORT"] = 587
app.config["MAIL_USE_TLS"] = True
app.config["MAIL_USERNAME"] = "apikey"
app.config[
"MAIL_PASSWORD"
] = "<Get it from SendGrid>"
app.config["MAIL_DEFAULT_SENDER"] = "<Test sender email>"
with app.app_context():
mail = Mail(app)
msg = Message("Twilio SendGrid Test Email", recipients=["<Test recipient email>"])
msg.body = "This is a test email!"
msg.html = "<p>This is a …
```
=> Add the integration guide for SendGrid as a reference to support sending emails

.vscode/settings.json, knowledge_repo/repositories/folder.py, run_tests.sh
When creating a new post with the `knowledge_repo` tool, missing REVISION or UUID files are expected, and should not lead to exception messages.
Test Plan:
CI
Reviewers:
=> Avoid printing-out exception errors when REVISION or UUID files are not found

README.md
A new section `Live Demo` was added to provide the URL link to the hosted demo website.
Test Plan:
CI
Reviewers:
=> Add the link to the live demo website

knowledge_repo/app/templates/index-feed.html, knowledge_repo/app/templates/index-table.html, knowledge_repo/app/templates/markdown-rendered.html, knowledge_repo/app/templates/tag_pages.html
Currently all tags are displayed with "#" prefix, which is unnecessary, and also could be confused with some real tag symbols, e.g., "C#".
Test Plan:
CI
Reviewers:
=> Remove the # symbol before tags to avoid unnecessary confusion

knowledge_repo/app/templates/base.html, knowledge_repo/app/templates/index-base.html, knowledge_repo/app/templates/index-cluster.html
When tags contain `#` or `.`, the cluster id generated does not behave correctly in HTML.
Test Plan:
CI
Reviewers:
=> Fix the cluster id issue with special characters `#` and `.` in tags

knowledge_repo/app/deploy/flask.py
In this refactored version, the `run` method has been split into two separate methods: `start` and `run`. The `start` method starts indexing, and the `run` method runs the application. This separation makes the code more readable and maintainable.
Test Plan:
CI
Reviewers:
=> Refactor the code in FlaskDeployer

knowledge_repo/app/routes/index.py
The size of `sitemap.xml` is too large now due to increasing number of posts, which could be compressed to be much smaller size with gzip.
Test Plan:
CI
Reviewers:
=> Use gzip to compress "sitemap.xml"

knowledge_repo/app/config_defaults.py
Indexing process could take more than 10 minutes, which was the old setting value. It caused early abortion of the indexing process.
Test Plan:
CI
Reviewers:
=> Increase the timeout value for indexing

.github/workflows/main.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/publish-to-test-pypi.yml, .vscode/launch.json, docker/Dockerfile
To use a local Git repo for development, a new launch configuration is added with appropriate settings. As Ubuntu `18.04` has been deprecated, it has been upgraded to `22.04`.
Test Plan:
CI
Reviewers:
=> Add a new launch setting for local development and upgrade the Ubuntu version
